repos:
  - repo: https://github.com/crate-ci/typos
    rev: typos-v0.10.14
    hooks:
      - id: typos
        args: []
        exclude: |
          (?x)(
              ^_site/|
              ^bin/|
              .*\.css$|
              .*\.scss$|
              .*\.html$|
              .*\.js$|
              .*\.json$|
              .*\.svg$|
              .*\.js.map$
          )
